### PR TITLE
Correct spelling of function pointer

### PR DESCRIPTION
**Pull request by per1234**
Previously, compilation would fail:
```
ESP8266-Remote-Message-Board-master\ESP8266_MAX7219_Message_Board_AP.ino\ESP8266_MAX7219_Message_Board_AP.ino.ino: In function 'void setup()':

ESP8266_MAX7219_Message_Board_AP.ino:71:17: error: 'GetMEssage' was not declared in this scope

   server.on("/",GetMEssage);

                 ^
```

Fixes https://github.com/G6EJD/ESP8266-Remote-Message-Board/issues/4

CC: @LenK13

### CODE REVIEW

**Comment by per1234** [comment]
Duplicated by:

- https://github.com/G6EJD/ESP8266-Remote-Message-Board/commit/894bfc4ab533050a32714f9722025a286111a990
- https://github.com/G6EJD/ESP8266-Remote-Message-Board/commit/80a0ce5feb7a709fd02ff3a9346d5d95e5cbcf4e

Ewww... You definitely need to work on your Git skills @G6EJD.

**Comment by G6EJD** [comment]
Is it working now?

**Comment by per1234** [comment]
It's too much work for me to check what you did because of the way you did it.

With my pull request, you have a nice [diff ](https://github.com/G6EJD/ESP8266-Remote-Message-Board/pull/5/files)that clearly shows what I changed and a commit message that explains why this was done. The change was done in a single atomic commit.

You don't need to upload the whole file with a new name and then delete the old file just to change a single character. In addition to being very inefficient, that also makes the diff and development history impossible to follow.

**Comment by G6EJD** [comment]
So changing E to e was too much work, perhaps the code is not good enough to meet your exacting standards, you could write your own variant and I look forward to seeing published for criticism in minute detail.

**Pull request closed without merging**
